#!/bin/sh
# klinpopup postrm

set -e

case "$1" in
    remove)
        if [ -x /usr/bin/update-menus ]; then
            /usr/bin/update-menus
        fi
        ;;
    purge)
        [ -d /var/lib/klinpopup ] && rmdir /var/lib/klinpopup 2>/dev/null || true
        ;;
    upgrade)
        ;;
    failed-upgrade)
        ;;
    abort-install)
        ;;
    abort-upgrade)
        ;;
    disappear)
        ;;
    *)
        echo "postrm called with unexpected argument '$1', ignored."
        ;;
esac
